---
# PHP installation and configuration
- name: Add PHP repository
  apt_repository:
    repo: ppa:ondrej/php
    state: present
    update_cache: yes

- name: Install PHP and modules
  apt:
    name: 
      - "php{{ php_version }}"
      - "php{{ php_version }}-fpm"
      - "{{ php_modules | map('regex_replace', '^php-', 'php' + php_version + '-') | list }}"
    state: present

- name: Configure PHP-FPM
  template:
    src: www.conf.j2
    dest: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
    backup: yes
  notify: restart php-fpm

- name: Configure PHP CLI
  template:
    src: php.ini.j2
    dest: "/etc/php/{{ php_version }}/cli/php.ini"
    backup: yes

- name: Configure PHP Apache module
  template:
    src: php.ini.j2
    dest: "/etc/php/{{ php_version }}/apache2/php.ini"
    backup: yes
  notify: restart apache

- name: Start and enable PHP-FPM
  systemd:
    name: "php{{ php_version }}-fpm"
    state: started
    enabled: yes

- name: Create PHP info file for testing
  template:
    src: info.php.j2
    dest: "{{ web_root }}/info.php"
    owner: www-data
    group: www-data
    mode: '0644'
  when: app_environment != 'production'