---
# System configuration tasks
- name: Set timezone
  timezone:
    name: "{{ timezone }}"
  notify: restart cron

- name: Set locale
  locale_gen:
    name: "{{ locale }}"
    state: present

- name: Update all packages
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600

- name: Install system packages
  apt:
    name: "{{ system_packages }}"
    state: present
    update_cache: yes

- name: Create project user
  user:
    name: "{{ project_name }}"
    shell: /bin/bash
    home: "/home/{{ project_name }}"
    create_home: yes
    system: no

- name: Create web directory
  file:
    path: "{{ web_root }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Configure automatic updates
  apt:
    name: unattended-upgrades
    state: present
  when: automatic_updates | default(false)

- name: Configure unattended upgrades
  template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    backup: yes
  when: automatic_updates | default(false)