---
# Security configuration tasks
- name: Install fail2ban
  apt:
    name: fail2ban
    state: present

- name: Configure fail2ban
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    backup: yes
  notify: restart fail2ban
  when: fail2ban_enabled | default(true)

- name: Start and enable fail2ban
  systemd:
    name: fail2ban
    state: started
    enabled: yes
  when: fail2ban_enabled | default(true)

- name: Configure UFW firewall
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ firewall_allowed_ports }}"
  when: ufw_enabled | default(true)

- name: Enable UFW
  ufw:
    state: enabled
    policy: deny
    direction: incoming
  when: ufw_enabled | default(true)

- name: Secure SSH configuration
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
  loop:
    - { regexp: '^#?PermitRootLogin', line: 'PermitRootLogin no' }
    - { regexp: '^#?PasswordAuthentication', line: 'PasswordAuthentication no' }
    - { regexp: '^#?PubkeyAuthentication', line: 'PubkeyAuthentication yes' }
    - { regexp: '^#?X11Forwarding', line: 'X11Forwarding no' }
    - { regexp: '^#?MaxAuthTries', line: 'MaxAuthTries 3' }
  notify: restart ssh

- name: Set secure file permissions
  file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
  loop:
    - { path: '/etc/ssh/sshd_config', mode: '0600' }
    - { path: '/etc/passwd', mode: '0644' }
    - { path: '/etc/shadow', mode: '0640' }
    - { path: '/etc/group', mode: '0644' }